Return Code: 1
Stdout: b'Free-threading result: [-6, -8, 4, 4, 0, -2, -1, -7, -9, 1]\n'
Stderr: b'Exception in thread Thread-10 (worker):\nTraceback (most recent call last):\n  File "/home/mrigankp/fuzz4py/cpython/Lib/threading.py", line 1041, in _bootstrap_inner\n    self.run()\n    ~~~~~~~~^^\n  File "/home/mrigankp/fuzz4py/cpython/Lib/threading.py", line 992, in run\n    self._target(*self._args, **self._kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/mrigankp/fuzz4py/fuzz4py/inputs/261.py", line 20, in worker\n    raise RuntimeError("Simulated error in thread")\nRuntimeError: Simulated error in thread\nTraceback (most recent call last):\n  File "/home/mrigankp/fuzz4py/fuzz4py/inputs/261.py", line 111, in <module>\n    jit_result = test_jit_compiler()\n  File "/home/mrigankp/fuzz4py/fuzz4py/inputs/261.py", line 43, in test_jit_compiler\n    raise ValueError("JIT error")\nValueError: JIT error\n'
